name: Test
on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20] 
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
          run_install: |
            # - recursive: true
            # args: [--frozen-lockfile, --strict-peer-dependencies]

    

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Install Playwright Browsers
        run: |
          npx playwright install chromium --with-deps
          npx playwright install firefox --with-deps
          npx playwright install webkit --with-deps

      - name: Run tests
        run: pnpm test:coverage && pnpm test:e2e

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

    